services:
  lunamultiplayer-server:
    build: .
    container_name: lunamultiplayer-server
    ports:
      - "8800:8800/udp"
      - "8801:8801/tcp"
    volumes:
      - ./server-data:/app/LMPServer/Universe
      - ./server-config:/app/LMPServer/Config
    restart: unless-stopped
    environment:
      - DOTNET_CLI_TELEMETRY_OPTOUT=1